// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLvjhPXMCrDKxXbDid95CAwyWzpBah0M4',
    appId: '1:121408025162:web:1afc953194898bb2ceacb3',
    messagingSenderId: '121408025162',
    projectId: 'trash-scout-3c117',
    authDomain: 'trash-scout-3c117.firebaseapp.com',
    storageBucket: 'trash-scout-3c117.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSb36r_dBENxcMCpDh4xGsBozUvvSIX0',
    appId: '1:121408025162:android:21c5666569ead8caceacb3',
    messagingSenderId: '121408025162',
    projectId: 'trash-scout-3c117',
    storageBucket: 'trash-scout-3c117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmm7OrQVEfyOM-D4T0gUbWR-4-OJdkCz0',
    appId: '1:121408025162:ios:ede0b773af5aa203ceacb3',
    messagingSenderId: '121408025162',
    projectId: 'trash-scout-3c117',
    storageBucket: 'trash-scout-3c117.appspot.com',
    iosBundleId: 'com.example.trashScout',
  );
}
